### ISSUE TITLE
[Bug] Double Page not fitting properly

### ISSUE THREAD

**Issue by AriaMoradi** [Suwayomi/Suwayomi-WebUI#112]
The Double Pages can overflow with no way of doin a horizontal scroll to see the content
<img width="1281" alt="Bildschirmfoto 2021-11-30 um 19 10 35" src="https://user-images.githubusercontent.com/5088968/144104128-912abca2-9fae-41e4-8837-64252064f608.png">

## Other details
Discovered during https://github.com/Suwayomi/Tachidesk-WebUI/pull/88

**Comment by schroda** [comment]
unable to reproduce, probably has been fixed
