### ISSUE TITLE
[Feature Request] Image scaling options when viewing manga

### ISSUE THREAD

**Issue by infyProductions** [Suwayomi/Suwayomi-WebUI#134]
## What feature should be added to Tachidesk?
Include a way to change the image scaling options to compensate different image sizes (in the reader sizes).

##  Why/Project's Benefit/Existing Problem
When reading manga (typically, from scanlation groups), resolutions are sometimes different (for example, the start and end pages are in 1280 x 720 [landscape], while the rest is in 720 x 1280 [portrait]). Some manga reading applications like YACReader (https://github.com/YACReader/yacreader) allows you to change the image scaling options [Fit Vertically/Horizontally, fill size, or fit page] (by pressing A) in order to compensate the fit with the device's screen resolution. 

In its current state, you either zoom the webpage all the way out to see the image in one go or change the orientation options in your settings and it is kinda inconvenient to have a good reading experience.

**Comment by schroda** [comment]
partially done
 - fit to window (#323)
 - change page width (#565)

**Comment by Dangonizer** [comment]
A hotkey to toggle "fit to window" would be great. Fit to window properly scales double pages but is really small for most single pages (at least on desktop) while set width works well for single pages but squishes the double pages.
