### ISSUE TITLE
[Feature Request] Download all, next 5,10 or unread chapters

### ISSUE THREAD

**Issue by BaccanoMob** [Suwayomi/Suwayomi-WebUI#17]
As title says, it be easier to download the selective chapters with a single click. This would help in preloading the chapters than waiting for it load.

**Comment by AriaMoradi** [comment]
oops

**Comment by EfeDevirgen** [comment]
up

**Comment by schroda** [comment]
closed by 52e077ff194dbcbb43451ba544f14e55a5f892da
