### ISSUE TITLE
[Feature Request] Shaders or color adjustment

### ISSUE THREAD

**Issue by xryanv** [Suwayomi/Suwayomi-WebUI#185]
I'd like to be able to have shaders that could be applied to the reader. What I'd like to see are adjustable filters for things like smoothing and sharpening, hue, contrast, brightness, vibrance, saturation, sepia etc. 

Also I'm not sure if it's possible but image upscalers would be cool too. I believe there are AI programs that can do this but perhaps this part is too complicated or slow I don't know.

**Comment by Robonau** [comment]
the filters a doable with css 
```css 
.class {
    filter: brightness(0.8)
}
``` 
for instance
but AI upscaling is well beyond the scope of tachidesk
