### ISSUE TITLE
[Feature Request] Put the "next chapter" button at the end of the chapter.

### ISSUE THREAD

**Issue by Gilz142** [Suwayomi/Suwayomi-WebUI#2]
Put the "next chapter" button and possibly the "previous chapter" button at the end of the chapter that is being read can make it easier for the users to navigate between chapters. This can prove helpful for those who are using the Tachidesk server remotely as well through browsers instead of having to open the navigation menu on the top left.
Just a suggestion.

**Comment by schroda** [comment]
done with #807
