### ISSUE TITLE
[Feature Request] Zoom levels for manwha/long strip content

### ISSUE THREAD

**Issue by lugia19** [Suwayomi/Suwayomi-WebUI#219]
## What feature should be added to Tachidesk?
The ability to zoom in/out of pages in the webUI, as they are as wide as the screen itself, which is weird for long strip content on desktop. Zooming out with the browser doesn't work either.

##  Why/Project's Benefit/Existing Problem
Images tend to look blurry when blown out this much, and it's awkward to read them like this. Having options for zoom levels would avoid the issue.

**Comment by schroda** [comment]
related to #134
