### ISSUE TITLE
[Feature Request] Design Suggestion for Reader Menu

### ISSUE THREAD

**Issue by iacore** [Suwayomi/Suwayomi-WebUI#289]
The current reader menu is confusing. I can't remember which is which. The cross button looks like it closes the menu, but it exits the reader.

![Screenshot](https://github.com/Suwayomi/Tachidesk-WebUI/assets/74560659/6331709a-71d1-4e06-accf-641cfb08ac2e)

This should be much better

![Revised](https://github.com/Suwayomi/Tachidesk-WebUI/assets/74560659/ddc2b7f8-d32d-4223-8cf1-3a23625ed66f)

This is even better

![Revised 4](https://github.com/Suwayomi/Tachidesk-WebUI/assets/74560659/37aa3248-4a2e-42a8-86ee-5857123621db)

**Comment by Underestimated** [comment]
I actually came here to suggest the same thing.
I’d be happy for it to be a toggle option in the settings, just give the option to flip the panel buttons around?

**Comment by schroda** [comment]
reader UI has been updated with #807
