### ISSUE TITLE
[Feature Request] Preload images in single page mode

### ISSUE THREAD

**Issue by Secozzi** [Suwayomi/Suwayomi-WebUI#662]
## What feature should be added to Suwayomi?
Make the reader only load a set number of pages ahead when reading, like how tachiyomi/mihon does.

##  Why/Project's Benefit/Existing Problem
Currently, single page mode will only load the page that is being displayed. That means that you have to wait for the page to load when going to the next page, when it could've been loaded when you're reading the current one.
On the contrary, every other reading mode will load the entire list of pages ahead when reading, but that can cause problems for servers that can't handle the load when loading potentially hundreds of pages, which is why it should only load a set (and small) number of pages ahead.

**Comment by schroda** [comment]
> On the contrary, every other reading mode will load the entire list of pages ahead when reading, but that can cause problems for servers that can't handle the load when loading potentially hundreds of pages, which is why it should only load a set (and small) number of pages ahead.

done with #639 + #624
