### ISSUE TITLE
[Bug] WebUI doesn't work on old devices

### ISSUE THREAD

**Issue by AleDema** [Suwayomi/Suwayomi-WebUI#672]
## Device information
- Suwayomi-Server version:v1.0.0-r1498-windows-x64
- Server Operating System: Windows 11
- Server Desktop Environment: N/A
- Server JVM version: bundled with win32
- Client Operating System: Android 4.4
- Client Web Browser:  Google Chrome 81.0.4044.138, Opera  58.8.2878.72999

## Steps to reproduce
1. Open React WebUI
2. Select a manga
3. Open any chapter

### Expected behavior
Images should load

### Actual behavior
Blank page

## Other details
The Svelte based UI is also broken, but in a different way: chapters load correctly but index and manga views don't. This is likely due to missing polyfills for outdated browsers.

**Comment by schroda** [comment]
UI version not provided
