### ISSUE TITLE
[Bug] Reader view doesn't load on old devices

### ISSUE THREAD

**Issue by AleDema** [Suwayomi/Suwayomi-WebUI#673]
## Device information
- Suwayomi-WebUI version: r1411 (any stable WebUI version since 1.0 release)
- Suwayomi-Server version:v1.0.0-r1498-windows-x64
- Server Operating System: Windows 11
- Server Desktop Environment: N/A
- Server JVM version: bundled with win32
- Client Operating System: Android 4.4
- Client Web Browser:  Google Chrome 81.0.4044.138, Opera 58.8.2878.72999

## Steps to reproduce
1. Open React WebUI
2. Select a manga
3. Open reader for any chapter

### Expected behavior
Images should load

### Actual behavior
Blank page

## Other details
The Svelte based UI is also broken, but in a different way: chapters load correctly but index and manga views don't. This is likely due to missing polyfills for outdated browsers.

**Comment by schroda** [comment]
you're on an 4 year old chrome version... the oldest one I was able to run was v93.0.4573.0, anything older than that didn't work at all

**Comment by AleDema** [comment]
Most browsers stopped being updated entirely on old devices, so they probably don't support modern js features. Importing Babel's polyfills should fix the issue.

**Comment by Syer10** [comment]
Dont use Chrome, use a supported browser. A quick Google search suggested Bromite, Kiwi, or Fennec for browsing the web on old devices

**Comment by AleDema** [comment]
Neither of those supports Android 4.4

**Comment by Syer10** [comment]
https://f-droid.org/en/packages/org.kiwix.kiwixmobile/
It says right there Android 4 or newer

**Comment by Syer10** [comment]
Nvm 2018
