### ISSUE TITLE
[Feature Request] Save search options on filters for sources

### ISSUE THREAD

**Issue by isabella-almeidaa** [Suwayomi/Suwayomi-WebUI#714]
## What feature should be added to Suwayomi?
An option to save filters on sources. TachiyomiSY has it. 

##  Why/Project's Benefit/Existing Problem
no need to filter everything again when searching for more stuff.

![image](https://github.com/Suwayomi/Suwayomi-WebUI/assets/157998949/d1a64ff3-07be-4bd5-9200-c4f876657d7d)
![image](https://github.com/Suwayomi/Suwayomi-WebUI/assets/157998949/f5f349d1-662b-4da0-80ac-46fc631d8516)

**Comment by schroda** [comment]
done with 5cb541b684347012dcdfcbdb86ad0c4600f97a21
