### ISSUE TITLE
[Feature Request] Add an option to multi select entries on sources

### ISSUE THREAD

**Issue by kana-shii** [Suwayomi/Suwayomi-WebUI#720]
## What feature should be added to Suwayomi?
Basically how multi select entries works on the library (with select all and etc), but in the sources instead, with an option to add the selected entries to the library.

##  Why/Project's Benefit/Existing Problem
Adding this option would save a lot of time when adding new things to the library

**Comment by schroda** [comment]
with #698 being integrated I don't see the benefit of having this

**Comment by kana-shii** [comment]
> with #698 being integrated I don't see the benefit of having this

I haven't seen this feature req before mb
ty for adding that
