### ISSUE TITLE
[Feature Request] Preloading a set number of pages ahead

### ISSUE THREAD

**Issue by Secozzi** [Suwayomi/Suwayomi-WebUI#724]
## What feature should be added to Suwayomi?
A way for webui to only preload a set number of pages ahead

##  Why/Project's Benefit/Existing Problem
Loading a set number of pages ahead will reduce the load on the servers, as new images will be loaded in accordance to the reading pace, as opposed to loading the entire list. Helps for sites that cannot handle the load, even with ratelimits.

**Comment by schroda** [comment]
done with #807
