### ISSUE TITLE
[Feature Request] add tracking to migration

### ISSUE THREAD

**Issue by kana-shii** [Suwayomi/Suwayomi-WebUI#744]
## What feature should be added to Suwayomi?
When migrating manga, tracking should be included. (Like in VUI)
![image](https://github.com/Suwayomi/Suwayomi-WebUI/assets/79055104/004b9876-636f-4e38-8cc2-7ca9e5b4bfaf)

##  Why/Project's Benefit/Existing Problem
No need to track titles again after migrating.

**Comment by schroda** [comment]
done with 2066851793e32973aa6811c8ed83b409d210b6aa
