### ISSUE TITLE
[Feature Request] Add an option to update tracking when marked as read.

### ISSUE THREAD

**Issue by kana-shii** [Suwayomi/Suwayomi-WebUI#748]
## What feature should be added to Suwayomi?
The tracker only updates when I get to the last page of the chapter. That's a problem because when I read online, I can't simply mark the chapter as read to have it update the tracker. This is an option in TachiyomiJ2K.

##  Why/Project's Benefit/Existing Problem
Easier way to track stuff. Sometimes suwayomi fails to load the chapters so I have to read on the site, so it would be much easier if this was added as an option.

Example:
![image](https://github.com/Suwayomi/Suwayomi-WebUI/assets/79055104/e83d3bb3-3325-4eb8-a4d5-6a8193855019)

**Comment by taos15** [comment]
This should be addressed with [PR 708](https://github.com/Suwayomi/Suwayomi-WebUI/pull/708) it will not update the tracker when you mark a chapter as read. But if you change the tracker read, it will update your local read. Technically it accomplishes the same, your read and track will be in sync. If you reas online, you set your track to that chapter that you read, and it will update your local as well.

**Comment by kana-shii** [comment]
> This should be addressed with [PR 708](https://github.com/Suwayomi/Suwayomi-WebUI/pull/708) it will not update the tracker when you mark a chapter as read. But if you change the tracker read, it will update your local read. Technically it accomplishes the same, your read and track will be in sync. If you reas online, you set your track to that chapter that you read, and it will update your local as well.

I'd rather have an separate option for that tho... MangaUpdates has been unstable for me for quite a while. Also, most of my titles have both MangaUpdates and MyAnimeList on them. That would probably mean that I would have to update both of them, right? Because if I only updates MyAnimeList, it would automatically update my local but it wouldn't update MangaUpdates, right?
And it would be even worse for the titles that have no entry on MyAnimeList.
For me to actually get access on MangaUpdates, I have to keep refreshing the page until it stops giving me an error message.
I think that your PR is really good but I don't think that it would actually make me change my mind about the importance of adding an option like the one that I requested.

**Comment by taos15** [comment]
> > This should be addressed with [PR 708](https://github.com/Suwayomi/Suwayomi-WebUI/pull/708) it will not update the tracker when you mark a chapter as read. But if you change the tracker read, it will update your local read. Technically it accomplishes the same, your read and track will be in sync. If you reas online, you set your track to that chapter that you read, and it will update your local as well.
> 
> 
> 
> I'd rather have an separate option for that tho... MangaUpdates has been unstable for me for quite a while. Also, most of my titles have both MangaUpdates and MyAnimeList on them. That would probably mean that I would have to update both of them, right? Because if I only updates MyAnimeList, it would automatically update my local but it wouldn't update MangaUpdates, right?
> 
> And it would be even worse for the titles that have no entry on MyAnimeList.
> 
> For me to actually get access on MangaUpdates, I have to keep refreshing the page until it stops giving me an error message.
> 
> I think that your PR is really good but I don't think that it would actually make me change my mind about the importance of adding an option like the one that I requested.

You are write. It will required you to update both tracker. It looks like the PR wont addressed the problem.

**Comment by schroda** [comment]
done with a1c0ec82b8916cc8aaa57b67c327cd6ef79dec9f and 1a16dba7bde48cc0f288f5a1974e192a1a255442
