### ISSUE TITLE
[Feature Request] warning message for duplicate entries and a duplicate entry detector

### ISSUE THREAD

**Issue by kana-shii** [Suwayomi/Suwayomi-WebUI#751]
## What feature should be added to Suwayomi?
A warning message when adding duplicate entries to the library and another feature to detect previous duplicate entries, giving out both duplicate entries through filters, or somewhere in the settings.

##  Why/Project's Benefit/Existing Problem
The warning message is something that already exists in Mihon and I'd say that it would be an important feature.
About the duplicate entry detector, it would be a lot easier than having to search through an extensive library to search for duplicates.

**Comment by schroda** [comment]
done with df66e180d88d5fb7bcf5a1290624dd26d539984e and f66051d39824ab0a7992d4426ac7538d34b180bb
