### ISSUE TITLE
[Feature Request] Unwanted update notification on clients when running in container

### ISSUE THREAD

**Issue by Apfelkuchenlab** [Suwayomi/Suwayomi-WebUI#752]
## What feature should be added to Suwayomi?
I am running suwayomi via the truecharts application container in TrueNAS Scale. Updates are handled this way, too. In web UI, Channel is set to stable.

However, any clients visiting the app, like phone browsers navigating to the page, will still see an "Update available" popup linking to the server preview github on every new session.

##  Why/Project's Benefit/Existing Problem
This is unwanted, since updates are not handled by the end users on these clients.

**Comment by Apfelkuchenlab** [comment]
Apologies, but I don't know where I can find this acknowledgment section or how I can remove it. I'd appreciate help on formatting this as you need it

**Comment by schroda** [comment]
done with 63543a48e32bc4190064b796691296077b255706
