### ISSUE TITLE
[Feature Request] Add inertia when using mouse navigation

### ISSUE THREAD

**Issue by bornav** [Suwayomi/Suwayomi-WebUI#759]
## What feature should be added to Suwayomi?
The goal would be to add if possible a toggleable option to make when reading in webtoon/continues vertical mode  so that on mouse release, it would take the speed of the release in count and continue to scroll the page like we have it when using touchscreens

##  Why/Project's Benefit/Existing Problem
For people who use drawing tablets or mouse as a form of navigation(in linux, browser recognizes tablet as a normal mouse)

**Comment by schroda** [comment]
done with #807
