### ISSUE TITLE
[Feature Request] Contextual menu at search manga list result

### ISSUE THREAD

**Issue by Gron21** [Suwayomi/Suwayomi-WebUI#766]
## What feature should be added to Suwayomi?
Add a Contextual menu for dowload option before access manga. When search from sources a manga name-> result a manga list -> in that screen, right-click on a manga open a contextual menu with download option.

##  Why/Project's Benefit/Existing Problem
It could help for less clicks to get manga... if you know that manga already or before...

**Comment by schroda** [comment]
browsing a source exists for you to add manga to your library, from which you can trigger downloads without having to open the manga page, so I don't intend to add this
