### ISSUE TITLE
[Feature Request] Show last uploaded chapter on search page

### ISSUE THREAD

**Issue by KiRa937** [Suwayomi/Suwayomi-WebUI#769]
## What feature should be added to Suwayomi?
When searching for manga the entries should show not only the cover+title, but also the last uploaded chapter plus time when it was uploaded.

##  Why/Project's Benefit/Existing Problem
When adding new titles different sources can have different number of chapters, some up to date, some way behind schedule. With this option it should be easier to pick title from the right source instead of checking them one by one. Also it can make Migrating easier when previously picked source stopped updating for some reason.

**Comment by schroda** [comment]
this information is not really known at that point of time.
the only manga that will have this data available are the ones that have been opened before, thus, there is also no guarantee that the data is up-to-date
