### ISSUE TITLE
[Feature Request] Toggle on/off autohide of the arrow button in dynamic navigation

### ISSUE THREAD

**Issue by Kickunio** [Suwayomi/Suwayomi-WebUI#775]
## What feature should be added to Suwayomi?
The arrow button when static navigation is off hides when scrolling pages down. To show it again, you have to scroll up, but the button is still available even when hidden.

##  Why/Project's Benefit/Existing Problem
The visibility of the little arrow button doesn't impede the reading experience, but the constant hiding creates a problem when you want to exit the reader, as you have to scroll up first and then click on the button.

Maybe it would be possible to have 2 buttons - one to enter settings and one to exit reader mode and go back to manga page/library that the setting would trigger the autohide ability on/off ?

**Comment by schroda** [comment]
reader UI has been updated with #807
