### ISSUE TITLE
[Feature Request] Multi Reload Data from Local Source

### ISSUE THREAD

**Issue by LadyHaywood** [Suwayomi/Suwayomi-WebUI#779]
## What feature should be added to Suwayomi?
A way to reload data from source for multiple books in library/local folder.

##  Why/Project's Benefit/Existing Problem
It would be nice to be able to reload multiple books from source instead of doing so one by one. I moved about 500 books locally to Suwayomi and some of them show up blank with broken covers until I reload it's data. It would just be easier if I can select all the blank ones and reload their data.

**Comment by LadyHaywood** [comment]
Updated the request to fix everything when I accidently posted it unfinished.

**Comment by schroda** [comment]
for now the only way to achieve this is to create a category for local source manga, add all of them to this category and then triggering a global update for only this category

triggering the global update for a specific category is only possible in the preview version of the webUI
