### ISSUE TITLE
[Feature Request] Update specific categories

### ISSUE THREAD

**Issue by holdenli** [Suwayomi/Suwayomi-WebUI#780]
## What feature should be added to Suwayomi?
In the library there should be a dropdown on the top right that allows me to do an update for the current category.

##  Why/Project's Benefit/Existing Problem
For large collections, I may not want to do a global update which can take a very long time. This also allows manual updating categories that are excluded from the global update in settings.

Note: This is a feature in Mihon and Tachidesk.

**Comment by schroda** [comment]
this already exists in the preview version
