### ISSUE TITLE
[Bug] WebUI reader goes to previous chapter

### ISSUE THREAD

**Issue by Kickunio** [Suwayomi/Suwayomi-WebUI#784]
## Device information
- Suwayomi-WebUI version: r1747
- Suwayomi-Server version: v1.1.1-r1548
- Server Operating System: docker
- Server Desktop Environment: docker
- Server JVM version: bundled
- Client Operating System: docker
- Client Web Browser: Google Chrome

## Steps to reproduce
1.Read manga normally and at the end go to next chapter (automatically or through next chapter button)

### Expected behavior
Reader goes to next chapter

### Actual behavior
Reader goes to previous chapter

## Other details
None

### Video
None

### Screenshots
None

**Comment by schroda** [comment]
fixed with b17fcd3
