### ISSUE TITLE
[Bug] Migrating mangas always get a "migration failed"

### ISSUE THREAD

**Issue by raidenii** [Suwayomi/Suwayomi-WebUI#786]
## Device information
- Suwayomi-WebUI version: r1689
- Suwayomi-Server version: v1.1.1
- Server Operating System: Debian 12, with Tachidesk running in Docker container
- Server Desktop Environment: N/A
- Server JVM version: openjdk version "11.0.23" 2024-04-16 (comes with Docker image)
- Client Operating System: Windows 11
- Client Web Browser: Firefox 128.1.0ESR

## Steps to reproduce
1. In tab Browse->Migrate, choose any manga to migrate from one source to another
2. Click migrate button in the popup

### Expected behavior
WebUI should return a message with success

### Actual behavior
The WebUI returns a "migration failed" message, but the manga was still actually migrated

## Other details
Docker logs when migration happens is attached.
[log.txt](https://github.com/user-attachments/files/16532976/log.txt)

This has been filed at server repo (https://github.com/Suwayomi/Suwayomi-Server/issues/1003), but I was told I should file it here instead.

**Comment by schroda** [comment]
should be fixed

related changes

- 782148a10e3dae9bc6166eff0b54fe670c64eb39
- 8ff67a38f0a5543f0df4a9868a42189e86e0ec70
- 4a01b1873ce85c55b086c1255711bc39bdb78575
- a29c113b5f23b556b186178441890514aa9fc359
