### ISSUE TITLE
[Feature Request] webui manga sort by file size

### ISSUE THREAD

**Issue by Michael7711** [Suwayomi/Suwayomi-WebUI#794]
## What feature should be added to Suwayomi?
Add an option to sort manga by total size on the Library page.

##  Why/Project's Benefit/Existing Problem
This feature would make it easier to manage server storage and remove large files. 

Additionally, some extensions may encounter issues where they download 0 pages, but the server incorrectly registers the download as complete. This feature would allow users to easily find and delete these manga, enabling them to re-download the correct files.

**Comment by schroda** [comment]
closing in favour of #801
