### ISSUE TITLE
[Bug] Incorrect behavior when in double page mode and chapter has spreads

### ISSUE THREAD

**Issue by drcorg** [Suwayomi/Suwayomi-WebUI#795]
## Device information
- Suwayomi-WebUI version: r1816
- Suwayomi-Server version: v1.1.1-r1566
- Server Operating System: Windows 11 
- Server Desktop Environment: N/A
- Server JVM version: bundled 
- Client Operating System: Windows 11
- Client Web Browser: Google Chrome 128.0.6613.113

## Steps to reproduce
1. Open a manga chapter that contains a spread while in double page mode.

### Expected behavior
While in double page mode, single pages preceding and succeeding spreads should be double paged unless unable to (i.e the spread is right after the first page, right before the last, or a single page is between two spreads).

### Actual behavior
In chapter with spreads, the pages before or after the spread will be displayed as single paged instead of double paged.

## Other details
This behavior seems to change based on whether the offset first page option is enabled. If the option is disabled, only the page before the spread will be a single, while if the option is enabled only the page after the spread will be a single. I've attached screenshots below.

### Screenshots
With offset first page disabled:
![image](https://github.com/user-attachments/assets/e9124515-93dd-4f5d-881b-b02eb63e27fb)
![image](https://github.com/user-attachments/assets/4a1f75db-96c8-4e89-a159-ff8647d987fb)
![image](https://github.com/user-attachments/assets/5efae63b-9d12-4cbd-9ee4-6c863dc4d17f)
With offset first page enabled:
![image](https://github.com/user-attachments/assets/f1f2648f-96ef-4eac-ba68-609ccbb9b8b5)
![image](https://github.com/user-attachments/assets/532aa2ac-5d19-4a28-8021-43bef33732ce)
![image](https://github.com/user-attachments/assets/ced94d70-9b68-4ae7-8578-3131468976d2)

**Comment by schroda** [comment]
unless someone else will fix it, it will be fixed with #778 (was added to the list)

**Comment by schroda** [comment]
should be fixed (83ce1caee631e73de16d2105b909d8c0bb9d3d5a, 5a46f1fdefbcdb4e28c08b322125efcf60870c57)
