### ISSUE TITLE
[Feature Request] optional Redirect to title page at end of chapter

### ISSUE THREAD

**Issue by Jerrk** [Suwayomi/Suwayomi-WebUI#796]
## What feature should be added to Suwayomi?
At the end of a chapter, with no next chapter available, give us an option to get redirected to the title page of the manga

##  Why/Project's Benefit/Existing Problem
This should be added since there is possibly some things you would like to do on the title page such as rating, changing tracker, bookmarking, deleting chapters, etc.

depending on how you opened the chapter "exit reader" might bring you to the library page instead of the title page, and then to enter the title page you might need to change your filters and search for the title to then enter it.

This would of course be optional, maybe toggled in reader settings. Could also possibly add a hyperlink in the "There is no next chapter to open" message that leads to the title page.

**Comment by schroda** [comment]
added to #778

**Comment by schroda** [comment]
done with #807
