### ISSUE TITLE
[Feature Request] Add chapter progress bars

### ISSUE THREAD

**Issue by Jerrk** [Suwayomi/Suwayomi-WebUI#797]
## What feature should be added to Suwayomi?
Instead of just showing the current page numbers i would suggest doing something like MDs progress bars

![image](https://github.com/user-attachments/assets/9cf8d665-c9e3-44d4-93ef-97ce2a1b0b57)

![image](https://github.com/user-attachments/assets/6fc8bbcb-3479-4880-ac90-df82725a4bbc)

![image](https://github.com/user-attachments/assets/a23e6a1d-391e-45af-b127-ccedaf78dbe4)

##  Why/Project's Benefit/Existing Problem
A more visually pleasing way to indicate your progress through a chapter.

**Comment by schroda** [comment]
added to #778

**Comment by schroda** [comment]
done with #807
