### ISSUE TITLE
[Feature Request] filters/sort options per category

### ISSUE THREAD

**Issue by Jerrk** [Suwayomi/Suwayomi-WebUI#802]
## What feature should be added to Suwayomi?
You should be able to set default filter/sort options when viewing a specific category.

If you're in the category "currently reading" you might only want to see "unread" chapters sorted by "latest uploaded chapter" whilst in the "dropped" category you might only want to see series with "downloaded" chapters

I find that when i move between categories i have to always change the filters and sort options to find what i'm looking for.

Another option is to remember the filter and sorting options per category instead of for the library as a whole. so if you change the options for the "reading" category it will not change the filters for the "completed" category and vice versa.

##  Why/Project's Benefit/Existing Problem
This should be added to make browsing your library easier by decreasing the amount of time used messing around with filters and sorting options.

**Comment by schroda** [comment]
done with a1131bf85b58b340a1b4f4c5781bb0ebf7fe9581
