### ISSUE TITLE
[Feature Request] hide inactive cursor

### ISSUE THREAD

**Issue by Jerrk** [Suwayomi/Suwayomi-WebUI#803]
## What feature should be added to Suwayomi?
if the reader notices that the cursor has not been moved in say 15 seconds it should hide the cursor.

Scrolling or clicking should not show the cursor, but moving it should.

Youtube has a similar function to this where while the video is playing the cursor will be hidden after about 5 seconds of not moving while on top of the video player.

##  Why/Project's Benefit/Existing Problem
This should be added because seeing the cursor may be a distraction while reading.

**Comment by schroda** [comment]
added to #778

**Comment by schroda** [comment]
done with #807
