### ISSUE TITLE
[Bug] translation issue, enum text from the server should be translatable

### ISSUE THREAD

**Issue by Robonau** [Suwayomi/Suwayomi-WebUI#806]
## Device information
- Suwayomi-WebUI version: n/a
- Suwayomi-Server version:n/a
- Server Operating System:n/a
- Server Desktop Environment: n/a
- Server JVM version: n/a
- Client Operating System: n/a
- Client Web Browser: n/a

## Steps to reproduce
this is mostly a remake of #805 since syer moved it and it got auto closed

the status text comes straight from the server rather than being translatable
weblate's Chinese translation is 100%

#805 points at local source too but i think that is fine to be untranslated idk

### Expected behavior
have the server enum text to translatable

### Actual behavior
its untranslated straight from the server 

### Screenshots
![image](https://github.com/user-attachments/assets/16535090-4ac0-49f8-92ae-c07f6b4f818d)

**Comment by schroda** [comment]
the status was already translated in the preview
local source is now also translated (da1a9d9e314b46b098cbf1e1b9afe124764d651f)
