### ISSUE TITLE
[Feature Request] Add descriptive filenames to downloaded images.

### ISSUE THREAD

**Issue by ItsGlassPlus1** [Suwayomi/Suwayomi-WebUI#811]
## What feature should be added to Suwayomi?
When saving images through the reader (i.e right click > save image as), add the name of the series and chapter title to the filename.

##  Why/Project's Benefit/Existing Problem
Currently, when you save images through the reader all saved files will be named solely with their page number. This means images can't be identified through their filenames and quickly you'll be prompted to overwrite existing files with the same name. Adding the name of the series and chapter title to the filename would also be in parity with Mihon.

**Comment by schroda** [comment]
I looked into it, but there seems to be no option to manually set the download name, the browser just takes the original file name from the server
