### ISSUE TITLE
[Feature Request] click dark part of screen to get out of set categories

### ISSUE THREAD

**Issue by aoba-seragakii** [Suwayomi/Suwayomi-WebUI#814]
## What feature should be added to Suwayomi?
make it so the user can exit the set categories screen when clicking on the dark part of the screen
![image](https://github.com/user-attachments/assets/4210d022-9b67-47c1-820a-6756bb988712)

it works like this on the tracking screen, it should also apply to the set categories screen
![image](https://github.com/user-attachments/assets/978f0f1d-e69e-4a18-80e4-8000159479bc)

**Comment by schroda** [comment]
done with 069aa26a0f2be91decec1f7153a640ff69b7e191
