### ISSUE TITLE
[Bug] download progresss stays the same during updates or downloads

### ISSUE THREAD

**Issue by xdeiimoss** [Suwayomi/Suwayomi-WebUI#818]
## Device information
- Suwayomi-WebUI version: r1936
- Suwayomi-Server version: v1.1.1-r1633
- Server Operating System: Windows11
- Server Desktop Environment: N/A
- Server JVM version: Java 21
- Client Operating System: Windows 11
- Client Web Browser: Opera

## Steps to reproduce
1. download or update library
2. check if % changes after a while
3. refresh when it doesn't and it shows up a completely different % than before

### Expected behavior
It shouldn't need any refreshes

### Actual behavior
It needs refreshes constantly to actually have the right %

**Comment by schroda** [comment]
this is a known bug in the current server preview version
