### ISSUE TITLE
[Feature Request] missing chapter warning

### ISSUE THREAD

**Issue by xdeiimoss** [Suwayomi/Suwayomi-WebUI#819]
## What feature should be added to Suwayomi?
a missing chapter warning just like Mihon
It shows on the page of the entry and when reading (if the next chapter has a different number, eg: you're reading chapter 74 and it goes to chapter 78, it'll tell that there are chapters being skipped)

other than that, something that would help would be a filter which detects which entries have missing chapters. It can help a lot by knowing which entries should be migrated as it's missing a chapter

**Comment by schroda** [comment]
missing chapter warning is shown in the reader (6dd2c8e2ffade0afd9bd82ec3a0f7696d4761819)

please keep it at one request per issue
- chapter list missing chapter warning moved to #836
- library filter for missing chapters moved to #836
