### ISSUE TITLE
[Bug] scale to width in new reader not working

### ISSUE THREAD

**Issue by Kickunio** [Suwayomi/Suwayomi-WebUI#830]
## Device information
- Suwayomi-WebUI version: r1975
- Suwayomi-Server version: v1.1.1-r1649
- Server Operating System: docker
- Server Desktop Environment: N/A
- Server JVM version: docker
- Client Operating System: docker
- Client Web Browser: Chrome

## Steps to reproduce
1. set scale type to image width
2. width doesn't change from default(even with limit)

### Expected behavior
Pages scale to width of the screen

### Actual behavior
Nothing changes

**Comment by schroda** [comment]
it only limits the pages to not get bigger than the available screen, it does not stretch small pages to take up the available width.
you have to enable "stretch small pages" for this to happen
