### ISSUE TITLE
[Bug] next chapter not opening in new reader

### ISSUE THREAD

**Issue by Kickunio** [Suwayomi/Suwayomi-WebUI#831]
## Device information
- Suwayomi-WebUI version: r1975
- Suwayomi-Server version: v1.1.1-r1649
- Server Operating System: docker
- Server Desktop Environment: N/A
- Server JVM version: docker
- Client Operating System: docker
- Client Web Browser: Chrome

## Steps to reproduce
1. scroll to the last page of the chapter
2. next chapter info shows up and next chapter doesn't load

### Expected behavior
Reader goes to next chapter automatically(like in old reader)

### Actual behavior
Nothing

**Comment by schroda** [comment]
This behaviour of the old reader does not exist anymore, you have to click once (the next page tap zone) for the next chapter to open.
This won't change until the "infinite scroll" has been implemented (see open tasks in #778)
