### ISSUE TITLE
[Bug] Webui Spams with Track requests

### ISSUE THREAD

**Issue by ptoump** [Suwayomi/Suwayomi-WebUI#845]
## Device information
- Suwayomi-WebUI version: r2017
- Suwayomi-Server version: v1.1.1-r1650
- Server Operating System: ubuntu 24.04 lts host - docker
- Server Desktop Environment: N/A - docker
- Server JVM version: docker
- Client Operating System: multiple, android, win 11
- Client Web Browser: firefox 133.0.3

## Steps to reproduce
1. Read a comic chapter to the end

### Expected behavior
Client should make a single chapter update request to the server

### Actual behavior
Client spams with tracker update requests

## Other details

I counted 79 identical requests.

![image](https://github.com/user-attachments/assets/87b0e6c5-8dd9-46d7-96a6-127666bad663)

### Screenshots

![image](https://github.com/user-attachments/assets/1afec59d-2fda-4a39-8497-3c7146a1358a)

**Comment by ptoump** [comment]
in another case it spamed hundreds of requests:

![image](https://github.com/user-attachments/assets/a2147b01-b480-4492-b5ac-e06d00315186)

**Comment by ptoump** [comment]
22 pages 292 requests. It happens on a single chapter, when I reach the end of it. The requests are all identical and they are made before a timeout is received. as you can see in the last sshot, it's 292 requests in 7,36s ..

**Comment by schroda** [comment]
fixed with b4c1cdee77fa76eed88bd5377aad58060b61cdd6, e95cc232a221849866c8a6f4d53d8eb54d3e2cb5
