### ISSUE TITLE
[Feature Request] Auto webtoon mode

### ISSUE THREAD

**Issue by xdeiimoss** [Suwayomi/Suwayomi-WebUI#847]
## What feature should be added to Suwayomi?
TachiSY has an Auto Webtoon mode, which detects the entries that are most likely to use the long strip mode. This is detected based on the tags of the entry (Manhwa, Webtoon)

**Comment by Jerrk** [comment]
Could also maybe analyze the pages to check their aspect ratio since a lot of webtoons use very tall pages compared to their width.

Not sure how feasible that is though since some sources crop the pages differently.

**Comment by schroda** [comment]
done with 33e184ba18a6d63de6d9ff4734cb932263cdd30f
