### ISSUE TITLE
[Feature Request] Filter by "started"

### ISSUE THREAD

**Issue by kkurootetsuro** [Suwayomi/Suwayomi-WebUI#855]
## What feature should be added to Suwayomi?
A filter which shows entries with at least one chapter read (Literally the same thing from the mihon one)

**Comment by schroda** [comment]
"literally the same thing as from the mihon one" exists with the same name and at exactly the same location?

**Comment by kkurootetsuro** [comment]
?? wdym
where?
![image](https://github.com/user-attachments/assets/6ee64fda-19f4-431a-833c-18a6d076a40d)

**Comment by schroda** [comment]
nevermind, I confused it with some other filter

**Comment by schroda** [comment]
done with 6c175d0b7f098cbb9f05b4614a24565c24e50edb
